=== gowtham789/IGATE_J2EE/test/WebBasics/Demos/Day4_FN/WB/products.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list_products">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="5" minOccurs="5" name="product">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[A-Za-z]+" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="price" type="xs:decimal" />
							<xs:element name="quantity" default="0">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0" />
										<xs:maxInclusive value="500" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:integer" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gowtham789/IGATE_J2EE/test/WebBasics/Demos/Day4_FN/WB/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<list_products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="products.xsd">
	<product id="101">
		<name>Pen</name>
		<price>10</price>
		<quantity></quantity>
	</product>
	<product id="102">
		<name>Pencil</name>
		<price>20</price>
		<quantity>30</quantity>
	</product>
	<product id="103">
		<name>Marker</name>
		<price>30</price>
		<quantity>70</quantity>
	</product>
	<product id="104">
		<name>Pen</name>
		<price>10</price>
		<quantity>500</quantity>
	</product>
	<product id="105">
		<name>Pen</name>
		<price>10</price>
		<quantity>20</quantity>
	</product>
</list_products>
